- package.json
- src/rsg-components/Preview/Preview.js
When I use vue-styleguidist to create a client-side npm-project when I declare styleguidist as a dependency, and because of `esprima` package is not specified explicitly in `package.json` - it gets resolved differently. I did see 2.7.3 and 4.0.0 versions in both of my yarn and npm lockfiles, but yarn resolves to 2.7.3 while npm to 4.0.0 in first-level `node_modules` folder. And Esprima at 2.7.3 used UMD, and for that, syntax like
```javascript
import esprima from 'esprima'
esprima.parse() // -- is ok
```
But for 4.0.0 Esprima migrated to Typescript (I think they migrated in 3.0.0 version), and it uses ES modules. And for that, former usage of module would break (because of how named exports). 
```javascript
import { parse } from 'esprima'
parse() // -- this would work
```
I tried to …
> Declare esprima as dependency in package.json

- docs/Documenting.md
This coincides with the pull request for vue-docgen-api to include the new @slot notation for documenting slots.
> Updating the documentation to include the new @slot notation

- loaders/utils/processComponent.js
Error "message is not defined" is thrown when the styleguide.config.js includes a "component" that is not a .vue file.
It's supposed to throw `Error when parsing ${filepath}:\n\n` + 'Only can parse files .vue:\n' (which it does after this fix)
> fix: wrong error when a non-vue file is in config

- bin/styleguidist.js
The `urls.localUrlForBrowser` is the string we want to supply to `opn`.
> Fixed opn URL when supplying --open CLI option

- README.md
`vue-styleguidist/buefy-styleguide-example` links to the deployed Buefy style guide, so it might be good to link to it from `vue-styleguidist/vue-styleguidist` too?
> Add link to deployed Buefy style guide to README

- package.json
We’ve been running into this issue with the latest versions of Vue StyleGuidist and tracked it down to be related to this same issue on React Styleguidist: https://github.com/styleguidist/react-styleguidist/issues/739 
I created a reduced test case in Codepen that replicates the issue in Safari: https://codepen.io/viljamis/pen/XZEaee
Updating jss-isolate to the latest (5.1.0) fixes the issue as it includes a fix for this Safari bug.
> Fixes font colors in examples being overwritten in Safari

- src/utils/scrollTo.js
I noticed that the scrollto functionality is broken in at least desktop Safari when using `navigation: true`. This is caused because the scrolling element in this case in Safari is actually `body` not `html`.
This pull should fix the functionality to work in any modern browser
> Fixes scrolling in Safari (and a few other browsers) when using navigation: true

- scripts/schemas/config.js
2 issues here:
- since we are using onely one type of files,
glob is consideruing {vue} to be a litteral 
I tried my new glob on http://www.globtester.com and it works with minimatch.
- no test or ignored file needs to be specified since we want All `.vue`
> fix: defaultConfig

- examples/nuxtjs/package.json
By default while trying to run Nuxt.js example is got these errors:
```
Error: Couldn't find preset "es2015" relative to directory "/Users/igloczek/Sites/temp/vue-styleguidist/examples/nuxtjs"
Warning: Cannot parse src/components/Logo.vue: Error: Error: Couldn't find preset "es2015" relative to directory "/Users/igloczek/Sites/temp/vue-styleguidist/examples/nuxtjs"
It usually means that vue-docgen-api does not understand your source code or when using third-party libraries, try to file an issue here:
https://github.com/vue-styleguidist/vue-docgen-api/issues
Error: Couldn't find preset "es2015" relative to directory "/Users/igloczek/Sites/temp/vue-styleguidist/examples/nuxtjs"
Warning: Cannot parse src/components/CounterButton/CounterButton.vue: Error: Error: Couldn't find preset "es2015" …
```
> Missing babel preset added to Nuxt.js example

- loaders/examples-loader.js
This simplifies greatly the examples loader by leveraging react-styleguidist modular architecture.
> Refactor - examples loader

- loaders/utils/getExamples.js
- loaders/utils/getProps.js
- loaders/utils/getSections.js
- loaders/vuedoc-loader.js
When I tried to use react-stykleguidist exampl-loader in order to lower the amount of code we are dealing with, I involuntarily changed the behaviour. Here is a quick fix of it ;).
closes #234
> fix(editor): html was rendered automaticaly by mistake

- src/rsg-components/Props/PropsRenderer.js
Rendering of props should not try to resolve pop-types or shapes as ghos do not exist in vuejs. instead, we might want to test vue-types validations but this is another story.
> fix: prop render needs to be vue oriented, not react oriented

- scripts/make-webpack-config.js
**Issue:** 
Vue is included twice in *main.bundle.js* when components are included from external package.
**Description:**
I want to have the styleguide separated from the components given a folder structue like that:
```
o
|-- components
|   |-- node_modules
|   |   `-- vue
|   `-- src
`-- styleguide
|-- node_modules
|   |-- *components
|   `-- vue
`-- src
```
The styleguide package was created by using vue-cli + vue-cli-plugin-styleguidist.
I have components package symlinked into the styleguide modules folder and importing those components like that:
*styleguide.config.js*
```
function resolveComponents(folder) {
return path.resolve(path.dirname(require.resolve('components/package.json')), folder);
};
sections: [
{
name: 'Components',
components: …
```
> Makes vue alias path absolute

- packages/vue-cli-plugin-styleguidist/ui/config.js
Ctrl-C Ctrl-V Driven Development (CCCVDD) ;-)
> fix(plugin/ui): mountPointId link was wrong

- .github/CONTRIBUTING.md
- docs/Development.md
- docs/Docgen.md
- docs/Documenting.md
- docs/VueCLI3doc.md
- docs/templates/Examples.md.ejs
Fix some spelling and grammar errors in the documentation
> Fix spelling and grammar in docs

- docs/Configuration.md
Link in docs to `editorConfig` option is broken. Path has changed
> Fix broken link to view editorConfig option

- docs/Configuration.md
Fixes link to DefaultExample.md link in docs
> fix DefaultExample.md link in docs

- packages/vue-docgen-api/src/utils/resolvePathFrom.ts
We are working with [Bazel](https://bazel.build/) which overrides the default nodejs require mechanisms as Bazel manages external dependencies itself and sets `node_modules` up differently. As a result we are getting some issues here with `vue-docgen-api` not finding some of our imported files. Just trying `require.resolve` as a fallback with an absolute path fixes the issue. While I was at it I also fixed the other path joining in this file.
Would be super helpful if we could get this in. Thanks!
> Try absolute require.resolve and fix path joining

- docs/docs/Documenting.md
I believe that `@property` should be `@type` in the event documentation examples
> Update event documentation examples

- docs/Configuration.md
- examples/basic/styleguide.config.js
- packages/vue-cli-plugin-styleguidist/ui/config.js
- packages/vue-styleguidist/scripts/make-webpack-config.js
- packages/vue-styleguidist/scripts/schemas/config.js
On Netlify, the build time can go to 12 min. If we make it optional I am convinced it can get it as low as 5 or less.
> feat: make mimimizing optional to optimize build time

- packages/vue-docgen-api/src/script-handlers/__tests__/slotHandler.ts
- packages/vue-docgen-api/src/script-handlers/slotHandler.ts
Hello. I found the issue that description for slot is ignored if you try to use pure js without JSX.
Here an example
```
export default {
render: function (createElement) {
return createElement(
'div', 
/** @slot Use this slot header */
this.$slots.mySlot
)
}
}
```
Code passes all tests, but i'm not 100% sure it doesn't brake uncovered places
Best wishes,
Sergey
> fix(docgen): get slot and scoped slot description in render without JSX

- packages/vue-docgen-api/src/utils/__tests__/resolveExportedComponent.ts
- packages/vue-docgen-api/src/utils/resolveExportedComponent.ts
- packages/vue-styleguidist/src/rsg-components/Props/PropsRenderer.js
@ffxsam I believe this one closes two of your issues.
> Fix: resolve typescript component that extend as VueCosntructor

- examples/basic/styleguide.config.js
- packages/vue-styleguidist/scripts/make-webpack-config.js
solarized variants are both stored in the same file
I split the value for the loaded file
Closes #480
> fix(codemirror): allow for mulitple words in cm themes

- packages/vue-styleguidist/loaders/examples-loader.js
- packages/vue-styleguidist/src/rsg-components/PlaygroundAsync/PlaygroundAsync.js
- packages/vue-styleguidist/src/rsg-components/Preview/PreviewAsync.js
- packages/vue-styleguidist/src/utils/processComponents.js
cc @JessicaSachs 
This is to avoid precompiling example with greedy buble while running the dev server.
> perf: only precompile example for prod

- packages/vue-docgen-cli/src/multiMd.ts
Thank you very much for having such an excellent open source project.
when we use `vue-docgen-cli` to get markdown files,we can config `destFile`,such as
```js
//docgen.config.js
module.exports = {
getDestFile: (file: string, config: DocgenCLIConfig) => path.join(config.outDir, file).replace(/\.vue$/ ".doc.md") // specify the name of the output md file
}
```
Sometimes we may have to do a lot of judgment work in the `getDestFile` custom function to determine whether we need to generate a markdown document.
such as in my config, i add a depth property,and in `getDestFile` to judge whether create md file!
> vue-docgen-cli add new feature (whether to create md files)

- examples/nuxtjs/package.json
In the `package.json` was a different path to the `styleguide.config.js`, the example didn't work.
> Fix: Nuxt example used wrong styleguide config path in package json

- packages/vue-docgen-api/src/main.ts
- packages/vue-docgen-api/tests/api/mock.vue
- packages/vue-docgen-api/tests/api/scriptHandlers.test.ts
Functions in the `DocGenOptions.addTemplateHandlers`  and `DocGenOptions.addScriptHandlers` were not being run because `isOptionsObject` was always returning false when passed an object unless it contained `opts.alias` or `opts.jsx`.
I think `nameFilter` and `modules` probably need to be added to the checks as well.
> Fix handlers

- packages/vue-docgen-api/README.md
- packages/vue-docgen-api/src/utils/__tests__/getDoclets.ts
- packages/vue-docgen-api/src/utils/getDoclets.ts
- packages/vue-docgen-api/src/utils/matchRecursiveRegexp.ts
The current version of the solution for identifying parameter types for strings containing "}" is incorrect
For example
```javascript
@param {{name: string}}
```
This pull request is trying to fix this bug
> fix(docgen): avoid incorrect of getting nested '}' param type

- docs/Configuration.md
- docs/docs/Cookbook.md
- docs/docs/Docgen.md
- packages/vue-docgen-api/README.md
- packages/vue-docgen-api/src/main.ts
- packages/vue-docgen-api/src/parse.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/extendsHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/mixinsHandler.ts
- packages/vue-docgen-api/src/script-handlers/extendsHandler.ts
- packages/vue-styleguidist/src/loaders/vuedoc-loader.ts
- packages/vue-styleguidist/src/scripts/schemas/config.ts
- packages/vue-styleguidist/src/types/StyleGuide.ts
> Feature: allow extending documentation from node_modules

- package.json
- packages/vue-docgen-api/src/Documentation.ts
- packages/vue-docgen-api/src/parse.ts
- packages/vue-docgen-api/src/script-handlers/extendsHandler.ts
- packages/vue-docgen-api/src/script-handlers/mixinsHandler.ts
- packages/vue-docgen-api/src/utils/__tests__/adaptExportsToIEV.ts
- packages/vue-docgen-api/src/utils/adaptExportsToIEV.ts
- packages/vue-docgen-api/tests/components/button/__snapshots__/button.test.ts.snap
- packages/vue-docgen-api/tests/components/class-component/__snapshots__/button-class.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/InputTextDocumented.test.ts
- packages/vue-docgen-api/tests/components/extended/InputTextDocumented.vue
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputText.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputTextDocumented.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputTextNatural.test.ts.snap
- packages/vue-docgen-api/tests/mixins/another/deep.js
- packages/vue-docgen-api/tests/mixins/multiNamed.js
- packages/vue-docgen-api/tests/perf-test.js
When resolvinf immediately exported variables 
```js
export foo from 'file/path'
```
I was not looking inside of `file/path` if it was an IEV as well which could lead to some unfortunate components not extended properly.
With this PR now I do.
> fix: resolve imediately exported variables recursively

- packages/vue-docgen-api/src/parse-script.ts
- packages/vue-docgen-api/src/parse.ts
- packages/vue-docgen-api/src/parseSFC.ts
- packages/vue-docgen-api/tests/components/jsfile/button-js.test.ts
- packages/vue-docgen-api/tests/components/multiple-exports/MyButton.vue
- packages/vue-docgen-api/tests/components/multiple-exports/multiple-exports.test.ts
When parsing components using `parse`, if it contains multiple components, documenting `export default` and return it.
If parsing using `parseMulti`, default comes as the first entry.
> Fix: make multiple exports safer

- packages/vue-docgen-api/src/utils/documentRequiredComponents.ts
Pass in modules to makePathResolver
closes #743
> fix (docgen): Use webpack modules when resolving paths

- docs/docs/GettingStarted.md
This wasn't clear to me originally, it just has a broken link if you aren't registered and logged into Vue Land.
> Make it clear that the discord link requires Vue Land account

- docs/docs/Docgen.md
There were some minor spelling mistakes that I noticed while reading the documentation, I did a quick run through, and fixed them. Thanks for styleguidist! It's really cool!
> docs: fix typos in docgen.md

- examples/nuxtjs-ts-property-decorator/src/components/SomeComponent.vue
- packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts
This is my first pr in this project, so I may be wrong.
Please, let me know if I don't follow contribution guide.
Currently, `vue-docgen-api` doesn't support proper union and intersection type.
This pr tries to fixes both.
I think it fixes #812 as well.
before (current version):
after (with this pr):
> fix(docgen):  fix ts array, intersection type print

- docs/docs/Docgen.md
- docs/docs/Documenting.md
Just a few little changes to the docs, both documenting the addition of custom doclet tags, as well as clearing up some confusion on things that have tripped me up in the past.
> docs: add clarification to some requirements

- packages/vue-docgen-api/src/script-handlers/__tests__/propHandler.ts
- packages/vue-docgen-api/src/script-handlers/classPropHandler.ts
- packages/vue-docgen-api/src/script-handlers/propHandler.ts
- packages/vue-docgen-api/tests/components/button/__snapshots__/button.test.ts.snap
- packages/vue-docgen-api/tests/components/button/button.test.ts
- packages/vue-docgen-api/tests/components/grid-jsx/__snapshots__/grid-jsx.test.ts.snap
- packages/vue-docgen-api/tests/components/grid-typescript/__snapshots__/grid-ts.test.ts.snap
- packages/vue-docgen-api/tests/components/grid/__snapshots__/grid.test.ts.snap
Fixes #852 
I add an overview to see all the tests I added. Each time the "expected" result has its whitespaces and new lines stripped to check the expected result. This means: **these whitespaces and new lines are still there, but not being tested**.
> Please let me know if you don't agree with any of these expected results!!
Two problems I ran into.
A bunch of snapshots were updated. These need to be reviewed if these changes are for the better or not. If not, last commit can be reverted.
While my tests all passed in the terminal, I had some trouble with the VSCode tests. They stayed grey:
I'm not sure why, or if I should worry about it. :D
I don't know what part of my VSCode was different, but the eventual commits seem to have some weird spacing... Feel free to fix these by auto …
> fix(docgen): correctly extract default values (pending review)
