- examples/basic/package.json
to update the basic example to use latest **webpack** and **vue-loader**
> Update package.json webpack & vue-webpack-loaders for basic example

- bin/styleguidist.js
in order to have a better understanding of the error
> show more info on unexpected errors

- docs/Webpack.md
For newbies like me it should become easier to find the correct configuration files, if the name of the file is mentioned.
> Extend description with file names

- examples/basic/src/components/Button/Readme.md
- loaders/utils/chunkify.js
- package.json
- src/rsg-components/Preview/Preview.js
- src/utils/singleFileComponentUtils.js
- src/utils/utils.js
Its implemented by essentially taking a Single File Component and converting it to the `new Vue({})` syntax.
> Add support for single file component format

- package.json
- yarn.lock
Pulls in changes for vue-styleguidist/vue-docgen-api#20
> Upgrade docgen-api dependency

- scripts/make-webpack-config.js
- scripts/schemas/config.js
This allows customization of assets link in generated html file
Basically I'd like a way to customize assets link in index.html generated by running `npm run styleguide:build`
> add public path config

- examples/vuecli3/Readme.md
- examples/vuecli3/babel.config.js
- examples/vuecli3/package.json
- examples/vuecli3/src/components/AppButton.vue
- examples/vuecli3/src/components/HelloWorld.vue
- examples/vuecli3/src/components/Readme.md
- examples/vuecli3/src/components/sizeMixin.js
- examples/vuecli3/styleguide.config.js
I am updating the example I created with the usage of the new plugin.
still a work in progress.
> update cli example with plugin

- .gitattributes
> Fix: add .gitattributes to avoid crlf issues

- .travis.yml
- bin/styleguidist.js
- package-lock.json
- package.json
BREAKING CHANGE - drop Webpack 3 support
> feat: update react styleguidist

- examples/basic/src/components/CounterButton/CounterButton.vue
- examples/basic/src/components/Input/Input.vue
- src/rsg-components/Events/EventsRenderer.js
I see that Pull Request #69 was openned by @greenzhang for 10 month. 
It took me 10 minutes to do the merge so, if you guys are keen on it, I will merge it tomorrow.
CC @social4hyq, @ozum, @sinkersan.
> feat: Add custom properties to the JSdoc

- loaders/utils/parseVue.js
> Fix LRUCache instantiation

- package-lock.json
- package.json
BREAKING CHANGE:  Events that are not commented near their call
will not anymore be parsed. If you want to document events,
do it as a leading comment before your event call
> feat: update docgen api to 3.0

- src/utils/singleFileComponentUtils.js
Okay I tried to make a first contribution, hopefully I did it right :smile:
fix #269
> allow vue code blocks without script parts in examples markdown

- loaders/vuedoc-loader.js
- package-lock.json
- package.json
> fix: implement webpack resolve feature in vsg

- scripts/config.js
- scripts/schemas/config.js
> fix: Enable serverPort config to accept string

- examples/customised/src/components/Button/Button.vue
- examples/customised/styleguide.config.js
- loaders/vuedoc-loader.js
> fix: alias and modules resolution needs to take styleguide.config into account

- docs/Cookbook.md
> docs(Cookbook.md): Updates theme variables link

- examples/customised/babel.config.js
- examples/customised/package-lock.json
- examples/customised/package.json
> Fix customized demo. Add missing babel plugin and node_module for jsx

- examples/basic/package-lock.json
- examples/basic/package.json
> Fix basic demo. Add missing dependencies in.

- examples/vuex/package-lock.json
- examples/vuex/package.json
Fixes issue #302 where the Vuex example didn't have vuex as a dependency.
> Fix vuex demo

- examples/nuxtjs/package-lock.json
- examples/nuxtjs/package.json
- examples/nuxtjs/styleguide/styleguide.config.js
> Fix nuxtjs demo.

- examples/nuxtjs/babel.config.js
- examples/nuxtjs/nuxt.config.js
- examples/nuxtjs/package.json
- examples/nuxtjs/src/components/Grid.vue
- examples/nuxtjs/src/components/RemoteGrid.vue
- examples/nuxtjs/src/pages/index.vue
- examples/nuxtjs/styleguide/styleguide.config.js
- examples/nuxtjs/styleguide/styleguide.root.js
- yarn.lock
this PR is to start the work on #244
> test(nuxtjs): try implementing modules

- docs/Cookbook.md
> docs(router): add how-to use router-link with vsg

- examples/basic/src/components/Placeholder/Placeholder.vue
- packages/vue-styleguidist/src/utils/__tests__/styleScoper.js
- packages/vue-styleguidist/src/utils/styleScoper.js
> fix(styleguide): fix scoped pseudo selectors

- .gitignore
and do some cleanup of the `.gitignore` file with some comments and some structure
> build(gitignore): ignore CSS artifacts of vue cli builds

- examples/basic/babel.config.js
- examples/basic/package.json
- examples/basic/styleguide.config.js
- package.json
- yarn.lock
> docs(examples): make basic example render on ie 11

- packages/vue-docgen-api/src/script-handlers/__tests__/componentHandler.ts
- packages/vue-docgen-api/src/script-handlers/componentHandler.ts
- packages/vue-docgen-api/tests/components/button/Button.vue
- packages/vue-docgen-api/tests/components/button/__snapshots__/button.test.ts.snap
- packages/vue-docgen-api/tests/components/button/button.test.ts
> fix(docgen): make displayName tag work

- packages/vue-cli-plugin-styleguidist/ui/config.js
- packages/vue-styleguidist/scripts/schemas/config.js
Hey @JessicaSachs 
What do you think of this refactoring?
Do you think it's a good idea ?
> refactor: single source of truth for Vue UI config

- packages/vue-docgen-api/package.json
- packages/vue-docgen-api/src/script-handlers/__tests__/mixinsHandler.ts
- packages/vue-docgen-api/src/script-handlers/extendsHandler.ts
- packages/vue-docgen-api/src/script-handlers/mixinsHandler.ts
- packages/vue-docgen-api/tests/components/dropdown/dropdown.test.ts
- packages/vue-docgen-api/tests/components/dropdown/dropdown.vue
- yarn.lock
> fix(docgen): fix node_modules mixins parsing

- packages/vue-styleguidist/src/rsg-components/VsgEditor/Editor.js
> fix(editor): make sure when url changes editor is repainted

- packages/vue-styleguidist/src/rsg-components/Preview/Preview.js
> fix(preview): fix style scope mismatch

- packages/vue-inbrowser-compiler/src/__tests__/isCodevueSfc.ts
- packages/vue-inbrowser-compiler/src/isCodeVueSfc.ts
> fix: detect pure template no script as sfc

- packages/vue-inbrowser-compiler/src/__tests__/isCodevueSfc.ts
- packages/vue-inbrowser-compiler/src/isCodeVueSfc.ts
> fix(docgen): template was used to use slots - sfc was detected

- packages/vue-docgen-api/src/script-handlers/__tests__/eventHandler.ts
- packages/vue-docgen-api/src/script-handlers/eventHandler.ts
> fix(docgen): fixed multiple use of same event needing desc

- packages/vue-docgen-api/src/template-handlers/__tests__/slotHandler.ts
- packages/vue-docgen-api/src/template-handlers/slotHandler.ts
> fix(docgen): make v-bind have a separate treatment

- docs/VueCLI3doc.md
- packages/vue-docgen-api/src/utils/__tests__/resolveAliases.ts
- packages/vue-docgen-api/src/utils/resolveAliases.ts
> fix(docgen): make aliases only path parts instead of letters

- packages/vue-docgen-api/src/Documentation.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/propHandler.ts
- packages/vue-docgen-api/src/script-handlers/propHandler.ts
- packages/vue-docgen-api/tests/components/button-external/__snapshots__/button-ext.test.ts.snap
- packages/vue-docgen-api/tests/components/button-typescript/__snapshots__/DatePicker-ts.test.ts.snap
- packages/vue-docgen-api/tests/components/button-typescript/__snapshots__/button-ts.test.ts.snap
- packages/vue-docgen-api/tests/components/button/__snapshots__/button.test.ts.snap
- packages/vue-docgen-api/tests/components/class-component/__snapshots__/button-class.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputText.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputTextDocumented.test.ts.snap
- packages/vue-docgen-api/tests/components/functional/InputWrapper-functional.test.ts
- packages/vue-docgen-api/tests/components/functional/InputWrapper.vue
- packages/vue-docgen-api/tests/components/functional/__snapshots__/InputWrapper-functional.test.ts.snap
- packages/vue-docgen-api/tests/components/grid-jsx/__snapshots__/grid-jsx.test.ts.snap
- packages/vue-docgen-api/tests/components/grid-typescript/__snapshots__/grid-ts.test.ts.snap
- packages/vue-docgen-api/tests/components/grid/__snapshots__/grid.test.ts.snap
> fix: model and value problem

- docs/Configuration.md
- examples/basic/styleguide.config.js
- packages/vue-cli-plugin-styleguidist/ui/config.js
- packages/vue-docgen-api/src/script-handlers/__tests__/classPropHandler.ts
- packages/vue-styleguidist/scripts/binutils.js
- packages/vue-styleguidist/scripts/make-webpack-config.js
- packages/vue-styleguidist/scripts/schemas/config.js
> feat: account for public path

- examples/basic/src/components/List/App.vue
- examples/basic/src/components/List/List.vue
- packages/vue-docgen-api/src/parse-template.ts
- packages/vue-docgen-api/tests/components/scoped-slot/App.vue
- packages/vue-docgen-api/tests/components/scoped-slot/Wrapper.vue
- packages/vue-docgen-api/tests/components/scoped-slot/__snapshots__/scoped-slot.test.ts.snap
- packages/vue-docgen-api/tests/components/scoped-slot/scoped-slot.test.ts
> fix: parse scoped slots

- examples/vuecli3/styleguide.config.js
- packages/vue-styleguidist/loaders/utils/processComponent.js
> feat: enhance skip no example

- packages/vue-styleguidist/src/rsg-components/VsgEditor/Editor.js
> fix: editor should update when changing page

- packages/vue-styleguidist/scripts/make-webpack-config.js
> fix: webpackConfig has priority on publicPath

- docs/Configuration.md
- packages/vue-docgen-cli/src/__tests__/docgen.ts
There seems to be some problem on line 458
> docs: renderRootJsx sample

- packages/vue-docgen-api/src/script-handlers/__tests__/classEventHandler.ts
- packages/vue-docgen-api/src/script-handlers/classEventHandler.ts
> feat(docgen): class event @emit

- packages/vue-docgen-api/src/script-handlers/__tests__/slotHandler.ts
- packages/vue-docgen-api/src/script-handlers/slotHandler.ts
> fix: look at statements for description

- packages/vue-inbrowser-compiler/src/__tests__/styleScoper.ts
- packages/vue-inbrowser-compiler/src/styleScoper.ts
> feat(compiler): styleScoper deals with deep

- packages/vue-docgen-api/src/script-handlers/__tests__/propHandler.ts
- packages/vue-docgen-api/src/script-handlers/propHandler.ts
> fix(docgen): allow default to be a method

- packages/vue-docgen-api/src/script-handlers/__tests__/slotHandler.ts
- packages/vue-docgen-api/src/script-handlers/slotHandler.ts
> fix(docgen): detetct scopedSlots in render()

- docs/docs/Documenting.md
Add information about public methods under Methods section.
> Add info about public method

- README.md
- docs/docs/Documenting.md
- packages/vue-docgen-api/src/utils/__tests__/resolveExportedComponent.ts
- packages/vue-docgen-api/src/utils/resolveExportedComponent.ts
- packages/vue-styleguidist/README.md
> feat(docgen): allow wrap export in if

- packages/vue-docgen-api/src/Documentation.ts
- packages/vue-docgen-api/src/parse.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/extendsHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/mixinsHandler.ts
- packages/vue-docgen-api/src/script-handlers/extendsHandler.ts
- packages/vue-docgen-api/src/script-handlers/mixinsHandler.ts
- packages/vue-docgen-api/tests/components/button/__snapshots__/button.test.ts.snap
- packages/vue-docgen-api/tests/components/class-component/__snapshots__/button-class.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputText.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputTextDocumented.test.ts.snap
> feat(docgen): add origin to documentation object

- examples/functional-flag/Readme.md
- examples/functional-flag/babel.config.js
- examples/functional-flag/package.json
- examples/functional-flag/src/components/Button/Button.vue
- examples/functional-flag/src/components/Button/Readme.md
- examples/functional-flag/src/components/Functional/FunctionalButton.vue
- examples/functional-flag/src/components/Functional/Readme.md
- examples/functional-flag/styleguide.config.js
- examples/functional-flag/styleguide/components/ComponentsListRenderer.js
- examples/functional-flag/styleguide/components/FunctionalTag.js
- examples/functional-flag/styleguide/components/ReactComponent.js
- examples/functional-flag/styleguide/components/SectionHeading.js
- examples/functional-flag/styleguide/components/SectionHeadingRenderer.js
- packages/vue-docgen-cli/src/compileTemplates.ts
- packages/vue-docgen-cli/src/extractConfig.ts
- packages/vue-docgen-cli/src/templates/component.ts
- packages/vue-docgen-cli/src/templates/functionalTag.ts
> New feature: display functional tag when necessary

- packages/vue-styleguidist/package.json
- packages/vue-styleguidist/src/scripts/binutils.ts
- yarn.lock
> feat: add progress bar while compiling

- packages/vue-cli-plugin-styleguidist/index.js
- packages/vue-styleguidist/scripts/index.js
> fix: make sure defaults are there for the plugin

- examples/customised/styleguide/components/StyleGuide.js
- examples/vueds/Readme.md
- examples/vueds/babel.config.js
- examples/vueds/package.json
- examples/vueds/src/components/BestButton/BestButton.vue
- examples/vueds/src/components/BestButton/Readme.md
- examples/vueds/src/components/Input/Input.vue
- examples/vueds/src/components/Input/Readme.md
- examples/vueds/src/components/Modal/Modal.vue
- examples/vueds/src/components/Modal/Readme.md
- examples/vueds/src/mixins/loggerMixin.js
- examples/vueds/styleguide.config.js
- examples/vueds/styleguide/components/Playground.js
- examples/vueds/styleguide/components/ReactComponent.js
- examples/vueds/styleguide/loadfont.js
- examples/vueds/styleguide/styles.js
- package.json
- yarn.lock
@viljamis I chose to create this example to see if I can reproduce your design-system with vsg 3-4 and React JSS standard. I hope you aprove.
closes #613
> Create an Example of Vue Styleguidist that looks like vue-design-system

- packages/vue-docgen-api/src/Documentation.ts
- packages/vue-docgen-api/src/parse-script.ts
- packages/vue-docgen-api/src/script-handlers/displayNameHandler.ts
- packages/vue-docgen-api/tests/components/button-external/__snapshots__/button-ext.test.ts.snap
- packages/vue-docgen-api/tests/components/button-noscript/__snapshots__/button-noscript.test.ts.snap
- packages/vue-docgen-api/tests/components/button-pug/__snapshots__/button-pug.test.ts.snap
- packages/vue-docgen-api/tests/components/button-typescript/__snapshots__/DatePicker-ts.test.ts.snap
- packages/vue-docgen-api/tests/components/button-typescript/__snapshots__/button-ts.test.ts.snap
- packages/vue-docgen-api/tests/components/button/__snapshots__/button.test.ts.snap
- packages/vue-docgen-api/tests/components/class-component/__snapshots__/button-class.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputText.test.ts.snap
- packages/vue-docgen-api/tests/components/extended/__snapshots__/InputTextDocumented.test.ts.snap
- packages/vue-docgen-api/tests/components/functional/__snapshots__/InputWrapper-functional.test.ts.snap
- packages/vue-docgen-api/tests/components/grid-jsx/__snapshots__/grid-jsx.test.ts.snap
- packages/vue-docgen-api/tests/components/grid-typescript/__snapshots__/grid-ts.test.ts.snap
- packages/vue-docgen-api/tests/components/grid/__snapshots__/grid.test.ts.snap
- packages/vue-docgen-api/tests/components/jsfile/MyButton.js
- packages/vue-docgen-api/tests/components/jsfile/button-js.test.ts
- packages/vue-docgen-api/tests/components/vuex/__snapshots__/example.test.ts.snap
- packages/vue-docgen-cli/src/templates/__tests__/defaultExample.ts
> Feature: add exportname to component doc

- packages/vue-docgen-api/src/script-handlers/componentHandler.ts
- packages/vue-docgen-api/tests/components/jsfile/MyButton.js
- packages/vue-docgen-api/tests/components/jsfile/button-js.test.ts
> fix(docgen): fixed description extraction on non-SFC components

- docs/docs/Docgen.md
Found typos while working on #638.
> docs: fix typos

- packages/vue-styleguidist/src/client/utils/compileExamples.ts
- packages/vue-styleguidist/src/client/utils/processComponents.ts
- packages/vue-styleguidist/src/client/utils/processSections.ts
> fix: make sections without examples pre-compile

- packages/vue-docgen-api/src/script-handlers/__tests__/classPropHandler.ts
- packages/vue-docgen-api/src/script-handlers/classPropHandler.ts
> fix(docgen): support @values on classPropHandler

- docs/Configuration.md
- docs/docs/Cookbook.md
- packages/vue-styleguidist/src/scripts/schemas/config.ts
- packages/vue-styleguidist/src/types/StyleGuide.d.ts
- packages/vue-styleguidist/templates/StyleGuide.d.ts.ejs
> chore: deliver

- docs/Configuration.md
- examples/sections/styleguide.config.js
- packages/vue-styleguidist/package.json
- packages/vue-styleguidist/src/scripts/schemas/config.ts
- packages/vue-styleguidist/src/types/StyleGuide.d.ts
- yarn.lock
> feat: collapsible sections

- packages/vue-styleguidist/src/loaders/utils/__tests__/getScript.spec.ts
- packages/vue-styleguidist/src/loaders/utils/getScript.ts
> fix: requires in SFC examples

- packages/vue-docgen-api/src/parse-script.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/classDisplayNameHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/classEventHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/classMethodHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/classPropHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/componentHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/displayNameHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/eventHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/extendsHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/methodHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/mixinsHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/propHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/slotHandler.ts
- packages/vue-docgen-api/src/script-handlers/extendsHandler.ts
- packages/vue-docgen-api/src/script-handlers/mixinsHandler.ts
- packages/vue-docgen-api/src/utils/__tests__/recursiveResolveIEV.ts
- packages/vue-docgen-api/src/utils/__tests__/resolveExportedComponent.ts
- packages/vue-docgen-api/src/utils/adaptExportsToIEV.ts
- packages/vue-docgen-api/src/utils/documentRequiredComponents.ts
- packages/vue-docgen-api/src/utils/recursiveResolveIEV.ts
- packages/vue-docgen-api/src/utils/resolveExportedComponent.ts
- packages/vue-docgen-api/tests/components/iev/iev.js
- packages/vue-docgen-api/tests/components/iev/iev.test.ts
- packages/vue-docgen-api/tests/components/iev/iev.vue
> Feature: accept immediately exported variables as valid components

- packages/vue-styleguidist/package.json
- yarn.lock
remove peer dependency preventing update of webpack
> Chore: allow updating webpack

- packages/vue-docgen-api/src/parseSFC.ts
- packages/vue-docgen-api/tests/components/docs-only/docs-only.test.ts
- packages/vue-docgen-api/tests/components/docs-only/docs.vue
> fix(docgen): docs only vue components

- packages/vue-docgen-api/src/utils/__tests__/resolveExportedComponent.ts
- packages/vue-docgen-api/src/utils/resolveExportedComponent.ts
> fix(docgen): filter components more clearly

- packages/vue-docgen-api/src/template-handlers/eventHandler.ts
- packages/vue-docgen-api/src/template-handlers/propHandler.ts
- packages/vue-docgen-api/tests/components/button-noscript/MyButton.vue
> fix(docgen): handle empty handler

- docs/Configuration.md
- examples/customised/styleguide.config.js
- examples/customised/styleguide/vsc-prism.css
- packages/vue-styleguidist/package.json
- packages/vue-styleguidist/src/client/rsg-components/VsgEditor/EditorPrism.js
- packages/vue-styleguidist/src/loaders/styleguide-loader.ts
- packages/vue-styleguidist/src/scripts/schemas/config.ts
- packages/vue-styleguidist/src/types/StyleGuide.d.ts
- yarn.lock
> Feature: allow usage of prism editor themes

- packages/vue-docgen-api/src/script-handlers/__tests__/methodHandler.ts
- packages/vue-docgen-api/src/script-handlers/methodHandler.ts
> Feature: methods returned by other methods

- packages/vue-docgen-api/src/utils/documentRequiredComponents.ts
- packages/vue-docgen-api/tests/components/button/button.test.ts
> fix(docgen): take mixin order into account

- packages/vue-cli-plugin-styleguidist/index.js
- packages/vue-styleguidist/src/bin/styleguidist.ts
- packages/vue-styleguidist/src/loaders/__tests__/examples-loader.ts
- packages/vue-styleguidist/src/loaders/styleguide-loader.ts
- packages/vue-styleguidist/src/loaders/utils/__tests__/getScript.spec.ts
- packages/vue-styleguidist/src/loaders/utils/getScript.ts
- packages/vue-styleguidist/src/loaders/vuedoc-loader.ts
- packages/vue-styleguidist/src/scripts/binutils.ts
- packages/vue-styleguidist/src/scripts/schemas/config.ts
> fix(plugin): pass cli options down to vsg

- packages/vue-docgen-api/src/utils/documentRequiredComponents.ts
- packages/vue-docgen-api/tests/components/iev/iev.js
- packages/vue-docgen-api/tests/components/iev/iev.test.ts
- packages/vue-docgen-api/tests/components/iev/ievNamed.vue
> fix(docgen): export iev var names

- docs/docs/Deployment.md
> fix(docs): Correct netlify build command

- examples/nuxtjs/package.json
- examples/vuecli3-class-pug-ts/package.json
- examples/vuecli3-vuetify-ie/package.json
- packages/vue-docgen-api/src/script-handlers/__tests__/classPropHandler.ts
- packages/vue-docgen-api/src/utils/getTypeFromAnnotation.ts
- packages/vue-docgen-api/tests/components/button-external/__snapshots__/button-ext.test.ts.snap
- packages/vue-docgen-api/tests/components/button-typescript/__snapshots__/button-ts.test.ts.snap
- packages/vue-styleguidist/package.json
- packages/vue-styleguidist/src/client/rsg-components/slots/UsageTabButton.tsx
- tsconfig.json
- yarn.lock
> Chore: update deps

- packages/vue-styleguidist/src/loaders/examples-loader.ts
- packages/vue-styleguidist/src/loaders/utils/getParser.ts
- packages/vue-styleguidist/src/loaders/vuedoc-loader.ts
> fix: default example parser with alias

- examples/basic/src/components/filters/Index.vue
- examples/basic/styleguide.config.js
- netlify/examples.yml
- packages/vue-docgen-api/src/parse.ts
- packages/vue-docgen-api/src/parseSFC.ts
- packages/vue-docgen-api/tests/components/button/__snapshots__/button.test.ts.snap
- packages/vue-docgen-api/tests/components/filters/Filters.vue
- packages/vue-docgen-api/tests/components/filters/Index.vue
- packages/vue-docgen-api/tests/components/filters/filters.test.ts
- packages/vue-docgen-api/tests/components/indexButton/index.vue
- packages/vue-docgen-api/tests/components/indexButton/indexButton.test.ts
- test/cypress/integration/basic/preview_spec.js
> feat(docgen): deal with index as filename

- package.json
- packages/vue-cli-plugin-styleguidist/index.js
- packages/vue-cli-plugin-styleguidist/package.json
- yarn.lock
> fix(plugin): update null-loader + avoid conflicts

- packages/vue-cli-plugin-styleguidist/empty-object-loader.js
- packages/vue-cli-plugin-styleguidist/index.js
- packages/vue-cli-plugin-styleguidist/package.json
- yarn.lock
Hey @DSC-CSTS I think I found a way.
> fix(plugin): use a custom loader to deal with docs

- docs/docs/Cookbook.md
- docs/docs/Docgen.md
- docs/docs/Documenting.md
- examples/vuetify/config/global.requires.js
- examples/vuetify/config/styleguide.root.js
- examples/vuetify/src/plugins/vuetify.js
- packages/vue-styleguidist/src/client/rsg-components/Preview/Preview.js
- packages/vue-styleguidist/src/scripts/schemas/config.ts
- packages/vue-styleguidist/src/types/StyleGuide.ts
> docs: update vuetify docs

- packages/vue-simple-docgen-loader/index.js
- packages/vue-simple-docgen-loader/package.json
- yarn.lock
> feat: add vue docgen simple loader

- packages/vue-docgen-api/src/script-handlers/__tests__/classPropHandler.ts
- packages/vue-docgen-api/src/script-handlers/__tests__/propHandler.ts
- packages/vue-docgen-api/src/script-handlers/classPropHandler.ts
- packages/vue-docgen-api/src/script-handlers/propHandler.ts
- packages/vue-docgen-api/src/utils/getDoclets.ts
> Feature: resolve @type doclet for props and values improvements

- packages/vue-docgen-api/src/script-handlers/__tests__/eventHandler.ts
- packages/vue-docgen-api/src/script-handlers/eventHandler.ts
- packages/vue-docgen-api/src/utils/getDocblock.ts
> feat(docgen): allow to force events definitions

- docs/docs/Cookbook.md
how to add styleguidist into nuxt
> docs: update Cookbook.md

- docs/docs/Cookbook.md
- docs/docs/Documenting.md
This adds a cookbook entry to the workaround proposed here: https://github.com/vue-styleguidist/vue-styleguidist/issues/770#issuecomment-633692858
> docs: add cookbook recipe for disaplyName (#770)
